const plannerData=()=>({expenses:Array.isArray(data.expenses)?data.expenses:[],goals:Array.isArray(data.goals)?data.goals:[]});
const daysPerMonth=30.4375;
function expenseDaily(e){const a=Number(e.amount)||0;return e.frequency==='daily'?a:e.frequency==='weekly'?a/7:a/daysPerMonth}
function daysUntil(date){const d=new Date(date+'T12:00:00');const t=new Date();t.setHours(12,0,0,0);return Math.max(0,Math.ceil((d-t)/86400000))}
function plannerSummary(){const p=plannerData(),dailyExpenses=p.expenses.reduce((s,e)=>s+expenseDaily(e),0),goalDaily=p.goals.reduce((s,g)=>{const remaining=Math.max(0,(Number(g.target)||0)-(Number(g.current)||0));const days=daysUntil(g.deadline);return s+(remaining/(days||1))},0),needed=dailyExpenses+goalDaily;return {dailyExpenses,goalDaily,needed,monthly:needed*daysPerMonth}}
function renderPlanner(){const p=plannerData(),s=plannerSummary();$('#plannerSummary').innerHTML=[['Daily expenses',money(s.dailyExpenses)],['Daily for goals',money(s.goalDaily)],['Necessary daily income',money(s.needed)],['Necessary monthly income',money(s.monthly)]].map((x,i)=>'<div class="planner-stat '+(i===2?'highlight':'')+'"><small>'+x[0]+'</small><strong>'+x[1]+'</strong></div>').join('');
$('#expensesList').innerHTML=p.expenses.length?p.expenses.map(e=>'<div class="planner-item"><div><div class="planner-item-title">'+esc(e.name)+'</div><div class="planner-item-meta">'+money(e.amount)+' / '+e.frequency+'</div></div><div class="planner-item-actions"><button class="secondary" onclick="editExpense(\''+e.id+'\')">Edit</button><button class="danger" onclick="deleteExpense(\''+e.id+'\')">Delete</button></div></div>').join(''):'<div class="planner-empty">No expenses added yet.</div>';
$('#goalsList').innerHTML=p.goals.length?p.goals.map(g=>{const target=Number(g.target)||0,current=Math.min(target,Number(g.current)||0),pct=target?Math.min(100,current/target*100):0,days=daysUntil(g.deadline),remaining=Math.max(0,target-current),daily=remaining/(days||1);return '<div class="planner-item"><div><div class="planner-item-title">'+esc(g.name)+'</div><div class="planner-item-meta">'+money(current)+' of '+money(target)+' · Deadline: '+esc(g.deadline||'—')+' · '+money(daily)+'/day needed</div><div class="goal-progress"><span style="width:'+pct+'%"></span></div></div><div class="planner-item-actions"><button class="secondary" onclick="editGoal(\''+g.id+'\')">Edit</button><button class="danger" onclick="deleteGoal(\''+g.id+'\')">Delete</button></div></div>'}).join(''):'<div class="planner-empty">No goals added yet.</div>'}}
function expenseForm(e={}){return '<div class="form-grid"><div class="form-field"><label>Expense name<input name="name" required value="'+esc(e.name||'')+'"></label></div><div class="form-field"><label>Amount<input name="amount" type="number" min="0" step=".01" required value="'+(e.amount??'')+'"></label></div><div class="form-field"><label>Frequency<select name="frequency"><option value="daily" '+(e.frequency==='daily'?'selected':'')+'>Daily</option><option value="weekly" '+(e.frequency==='weekly'?'selected':'')+'>Weekly</option><option value="monthly" '+(e.frequency==='monthly'||!e.frequency?'selected':'')+'>Monthly</option></select></label></div></div><div class="form-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save Expense</button></div>'}
function addExpense(){showModal('Add Expense',expenseForm());$('#modalForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.expenses.push({id:uid('expense'),name:f.get('name'),amount:+f.get('amount')||0,frequency:f.get('frequency')});closeModal();renderPlanner();autoSaveDatabase();setStatus('Expense added and saved.',true)}}
function editExpense(id){const e=data.expenses.find(x=>x.id===id);if(!e)return;showModal('Edit Expense',expenseForm(e));$('#modalForm').onsubmit=x=>{x.preventDefault();const f=new FormData(x.target);Object.assign(e,{name:f.get('name'),amount:+f.get('amount')||0,frequency:f.get('frequency')});closeModal();renderPlanner();autoSaveDatabase();setStatus('Expense updated and saved.',true)}}
function deleteExpense(id){if(confirm('Delete this expense?')){data.expenses=data.expenses.filter(x=>x.id!==id);renderPlanner();autoSaveDatabase();setStatus('Expense deleted and saved.',true)}}
function goalForm(g={}){return '<div class="form-grid"><div class="form-field"><label>Goal name<input name="name" required value="'+esc(g.name||'')+'"></label></div><div class="form-field"><label>Target amount<input name="target" type="number" min="0" step=".01" required value="'+(g.target??'')+'"></label></div><div class="form-field"><label>Already saved<input name="current" type="number" min="0" step=".01" value="'+(g.current??0)+'"></label></div><div class="form-field"><label>Target date<input name="deadline" type="date" required value="'+(g.deadline||'')+'"></label></div></div><div class="form-actions"><button type="button" class="secondary" onclick="closeModal()">Cancel</button><button class="primary">Save Goal</button></div>'}
function addGoal(){showModal('Add Goal',goalForm());$('#modalForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.goals.push({id:uid('goal'),name:f.get('name'),target:+f.get('target')||0,current:+f.get('current')||0,deadline:f.get('deadline')});closeModal();renderPlanner();autoSaveDatabase();setStatus('Goal added and saved.',true)}}
function editGoal(id){const g=data.goals.find(x=>x.id===id);if(!g)return;showModal('Edit Goal',goalForm(g));$('#modalForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);Object.assign(g,{name:f.get('name'),target:+f.get('target')||0,current:+f.get('current')||0,deadline:f.get('deadline')});closeModal();renderPlanner();autoSaveDatabase();setStatus('Goal updated and saved.',true)}}
function deleteGoal(id){if(confirm('Delete this goal?')){data.goals=data.goals.filter(x=>x.id!==id);renderPlanner();autoSaveDatabase();setStatus('Goal deleted and saved.',true)}}
function initPlanner(){const eb=$('#addExpenseBtn'),gb=$('#addGoalBtn');if(eb)eb.addEventListener('click',function(e){e.preventDefault();addExpense()});if(gb)gb.addEventListener('click',function(e){e.preventDefault();addGoal()});renderPlanner()} if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',initPlanner)}else{initPlanner()}